name: Build and deploy jekyll site

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ¬ Setup
        uses: actions/checkout@v2
      - name: ğŸ’ Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: ğŸ’¾ Cache 
        uses: actions/cache@v2  # This action allows caching dependencies and build outputs to improve workflow execution time.
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: ğŸ”§ Build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: .
          gem_src: .
      - name: ğŸ” Algolia Jekyll Action
        run: ALGOLIA_API_KEY='${{ secrets.ALGOLIA_API_KEY }}' bundle exec jekyll algolia
      # - name: ğŸ” Algolia Jekyll Action
      #   uses: dieghernan/algolia-jekyll-action@v1
      #   with:
      #     APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
      - name: ğŸš€ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: true